name: jpy39
channels:
  - bokeh
  - defaults
dependencies:
  - altair=4.1.0
  - appdirs=1.4.4
  - async_generator=1.10
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates
  - certifi=2022.6.15
  - cffi=1.14.6
  - cftime=1.5.1.1
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cloudpickle=2.0.0
  - colorcet=2.0.6
  - cryptography=36.0.0
  - curl=7.80.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask=2021.10.0
  - dask-core=2021.10.0
  - datashader=0.13.0
  - datashape=0.5.4
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - distributed=2021.10.0
  - entrypoints=0.3
  - et_xmlfile=1.1.0
  - fonttools=4.25.0
  - fsspec=2022.1.0
  - giflib=5.2.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - holoviews=1.14.6
  - hvplot=0.7.3
  - hypothesis=6.29.3
  - idna=3.3
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_bokeh=3.0.4
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - libcurl=7.80.0
  - libllvm10=10.0.1
  - libnetcdf=4.6.1
  - locket=0.2.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.2
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclient=0.5.3
  - nest-asyncio=1.5.1
  - netcdf4=1.5.7
  - notebook=6.4.6
  - numba=0.53.1
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openpyxl=3.0.10
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.4.3
  - panel=0.12.1
  - param=1.12.0
  - parso=0.8.3
  - partd=1.2.0
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pyct=0.4.6
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyrsistent=0.18.0
  - pyserial=3.5
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyviz_comms=2.0.2
  - pyyaml=6.0
  - requests=2.27.1
  - scipy=1.7.3
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.37.0
  - statsmodels=0.13.0
  - tbb=2020.3
  - tblib=1.7.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.1
  - xarray=0.20.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - anyio==3.5.0
    - babel==2.9.1
    - black==21.12b0
    - blackcellmagic==0.0.3
    - iqplot==0.2.4
    - json5==0.9.6
    - jupyter==1.0.0
    - jupyter-console==6.4.0
    - jupyter-server==1.13.3
    - jupyterlab==3.2.8
    - jupyterlab-server==2.10.3
    - jupyterlab-spellchecker==0.7.2
    - nbclassic==0.3.5
    - pathspec==0.9.0
    - platformdirs==2.4.1
    - pypng==0.20220715.0
    - pyreadstat==1.1.4
    - qrcode==7.4.2
    - qtconsole==5.2.2
    - qtpy==2.0.0
    - sniffio==1.2.0
    - tomli==1.2.3
    - watermark==2.3.0
    - websocket-client==1.2.3